---

- name: Wazuh | create /etc/modprobe.d/ for modprobe conf files
  file:
    path: /etc/modprobe.d
    state: directory

- name: Wazuh | 2506 | Ensure mounting of FAT filesystems is disabled | modprobe
  modprobe:
    name: vfat
    state: absent
  when: disable_vfat

- name: Wazuh | 2506 | Ensure mounting of FAT filesystems is disabled | /etc/modprobe.d/
  lineinfile:
    dest: /etc/modprobe.d/vfat.conf
    regexp: "^.*install vfat.*$"
    line: "install vfat /bin/true"
    state: present
    create: true
  when: disable_vfat

- name: Wazuh | 2524 | Disable USB Storage | /etc/modprobe.d/
  lineinfile:
    dest: /etc/modprobe.d/usb_storage.conf
    regexp: "^.*install usb-storage.*$"
    line: "install usb-storage /bin/true"
    state: present
    create: true

- name: Wazuh | 2524 | Disable USB Storage | modprobe
  modprobe:
    name: usb-storage
    state: absent

- name: Wazuh | create /etc/sudoers.d/ for sudo conf files
  file:
    path: /etc/sudoers.d
    state: directory

- name: Wazuh | 2526 | Ensure sudo commands use pty
  lineinfile:
    dest: /etc/sudoers.d/pty
    regexp: "^.*Defaults use_pty.*"
    line: "Defaults use_pty"
    validate: "visudo -cf %s"
    create: yes
    state: present

- name: Wazuh | 2527 | Ensure sudo log file exists
  lineinfile:
    dest: /etc/sudoers.d/sudo_logs
    regexp: "^.*Defaults logfile.*"
    line: 'Defaults logfile="/var/log/sudo.log"'
    validate: "visudo -cf %s"
    create: yes
    state: present

- name: Wazuh | 2528 | Ensure AIDE is installed | apt
  apt:
    pkg:
    - aide
    - aide-common

- name: Wazuh | 2528 | Ensure AIDE is installed | DB stat
  stat: path=/var/lib/aide/aide.db
  register: aide_db_stat

- name: Wazuh | 2528 | Ensure AIDE is installed | init
  shell: aideinit
  args:
    executable: /bin/bash
  when: aide_db_stat.stat.exists == False

- name: Wazuh | 2528 | Ensure AIDE is installed | DB new stat
  stat: path=/var/lib/aide/aide.db.new
  register: aide_db_new_stat

- name: Wazuh | 2528 | Ensure AIDE is installed | DB copy
  copy:
    src: /var/lib/aide/aide.db.new
    dest: /var/lib/aide/aide.db
  when: 
    - aide_db_new_stat.stat.exists
    - aide_db_stat.stat.exists == False

- name: Wazuh | 2528 | Ensure AIDE is installed | DB new delete
  file:
    path: /var/lib/aide/aide.db.new
    state: absent

- name: Wazuh | 2529 | Ensure filesystem integrity is regularly checked
  cron:
    name: AIDE filesystem check
    user: root
    minute: "0"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/aide --config /etc/aide/aide.conf --check"

- name: Wazuh | 2530 | Ensure permissions on bootloader config are configured
  file:
    path: "/boot/grub/grub.cfg"
    mode: "og-rwx"
    owner: root
    group: root

######## TO DO ########
### - name: Wazuh | 2531 | Ensure bootloader password is set

- name: Wazuh | 2532 | Ensure authentication required for single user mode
  shell: grep "^root:[*\!]:" /etc/shadow
  register: root_password_check
  changed_when: false
  failed_when: false
  check_mode: no

- name: Wazuh | 2532 | Ensure authentication required for single user mode | generate password
  set_fact:
    root_password: "{{ root_password_gen }}"
  when: 
    - root_password_check.rc != "0"

- name: change password
  ansible.builtin.user:
    name: "root"
    state: present
    password: "{{ root_password }}"
  when: 
    - root_password_check.rc != "0"
