---

- name: Debian 11 Aparavi
  hosts: 
    - "all"
  become: true
  gather_facts: true
  roles:
    # - mysql_server
    - os_hardening
    - ssh_hardening
    # - prometheus-node-exporter
    # - rapid7-agent
    - my_hardening
    - wazuh-agent
    # - clamav-agent
  vars:
    - ssh_client_password_login: true
    - ssh_server_password_login: true
    - sshd_authenticationmethods: "publickey password"
    - disable_vfat: false
    # Wazuh | 2656 | Ensure only strong MAC algorithms are used
    - ssh_macs: ["hmac-sha2-512-etm@openssh.com", "hmac-sha2-256-etm@openssh.com", "hmac-sha2-512", "hmac-sha2-256"]
    # Wazuh | 2660 | Ensure SSH access is limited
    - sh_deny_users: "root"
    # Wazuh | 2661 | Ensure SSH warning banner is configured
    - ssh_banner: "true"
    - ssh_banner_path: "/etc/issue.net"
  tasks:
    - name: Flush handlers
      meta: flush_handlers
    - name: Extra | Retrieving root password (if changed)
      debug:
        msg: 
          - "New root password: {{ root_password }}"
          - "It's necessary to have a password for root user. Wazuh 2532."
          - "Compliance: cis 1.5.3; cis_csc 5.1; nist_800_53 CM.1; pci_dss 2.2.4; tsc CC5.2"
      when: root_password is defined
