---
- name: Restart systemd-timesyncd
  service:
    name: "systemd-timesyncd"
    state: restarted

- name: Wazuh | 2576 | chmod grub.conf
  file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: 0400

- name: Wazuh | 2576 | update-grub
  command: /usr/sbin/update-grub
  notify: Wazuh | 2576 | chmod grub.conf

- name: Wazuh | 2579 | ipv4 route flush
  command: sysctl -w net.ipv4.route.flush=1

- name: Wazuh | 2579 | ipv6 route flush
  command: sysctl -w net.ipv6.route.flush=1

- name: Wazuh | 2629 |  rsyslog restart
  service:
    name: rsyslog
    state: restarted

- name: passwd- group- permissions
  file:
    dest: '{{ item }}'
    mode: "u-x,go-rwx"
  loop:
    - /etc/passwd-
    - /etc/group-


- name: log permissions
  block:
    - name: find files
      find:
        paths: /var/log
        recurse: yes
        file_type: file
      register: files_in_var_log

    - name: set files permissions
      file:
        dest:  '{{ item.path }}'
        mode: "g-wx,o-rwx"
      loop: '{{ files_in_var_log.files }}'
      notify: var_log_permissions

    - name: find dirs
      find:
        paths: /var/log
        recurse: yes
        file_type: directory
      register: directories_in_var_log

    - name: set dirs permissions
      file:
        dest: '{{ item.path }}'
        mode: "g-w,o-rwx"
      loop: '{{ directories_in_var_log.files }}'
      notify: var_log_permissions
